package model;
// Generated Feb 26, 2017 7:54:18 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int userId;
     private String username;
     private String password;
     private String email;
     private Serializable fullname;
     private Serializable address;
     private String phone;
     private boolean gender;
     private Date birthdate;
     private boolean isAdmin;
     private Set<Review> reviews = new HashSet<Review>(0);
     private Set<Transaction> transactions = new HashSet<Transaction>(0);

    public User() {
    }

	
    public User(int userId, String username, String password, String email, Serializable fullname, boolean gender, Date birthdate, boolean isAdmin) {
        this.userId = userId;
        this.username = username;
        this.password = password;
        this.email = email;
        this.fullname = fullname;
        this.gender = gender;
        this.birthdate = birthdate;
        this.isAdmin = isAdmin;
    }
    public User(int userId, String username, String password, String email, Serializable fullname, Serializable address, String phone, boolean gender, Date birthdate, boolean isAdmin, Set<Review> reviews, Set<Transaction> transactions) {
       this.userId = userId;
       this.username = username;
       this.password = password;
       this.email = email;
       this.fullname = fullname;
       this.address = address;
       this.phone = phone;
       this.gender = gender;
       this.birthdate = birthdate;
       this.isAdmin = isAdmin;
       this.reviews = reviews;
       this.transactions = transactions;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Serializable getFullname() {
        return this.fullname;
    }
    
    public void setFullname(Serializable fullname) {
        this.fullname = fullname;
    }
    public Serializable getAddress() {
        return this.address;
    }
    
    public void setAddress(Serializable address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public boolean isGender() {
        return this.gender;
    }
    
    public void setGender(boolean gender) {
        this.gender = gender;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public boolean isIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public Set<Review> getReviews() {
        return this.reviews;
    }
    
    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews;
    }
    public Set<Transaction> getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set<Transaction> transactions) {
        this.transactions = transactions;
    }




}


