package model;
// Generated Feb 26, 2017 7:54:18 PM by Hibernate Tools 4.3.1



/**
 * CartItem generated by hbm2java
 */
public class CartItem  implements java.io.Serializable {


     private CartItemId id;
     private Product product;
     private Transaction transaction;
     private int quantity;

    public CartItem() {
    }

    public CartItem(CartItemId id, Product product, Transaction transaction, int quantity) {
       this.id = id;
       this.product = product;
       this.transaction = transaction;
       this.quantity = quantity;
    }
   
    public CartItemId getId() {
        return this.id;
    }
    
    public void setId(CartItemId id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Transaction getTransaction() {
        return this.transaction;
    }
    
    public void setTransaction(Transaction transaction) {
        this.transaction = transaction;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


