package model;
// Generated Feb 26, 2017 7:54:18 PM by Hibernate Tools 4.3.1



/**
 * CartItemId generated by hbm2java
 */
public class CartItemId  implements java.io.Serializable {


     private int transactionId;
     private int productId;

    public CartItemId() {
    }

    public CartItemId(int transactionId, int productId) {
       this.transactionId = transactionId;
       this.productId = productId;
    }
   
    public int getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(int transactionId) {
        this.transactionId = transactionId;
    }
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CartItemId) ) return false;
		 CartItemId castOther = ( CartItemId ) other; 
         
		 return (this.getTransactionId()==castOther.getTransactionId())
 && (this.getProductId()==castOther.getProductId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTransactionId();
         result = 37 * result + this.getProductId();
         return result;
   }   


}


