package model;
// Generated Feb 26, 2017 7:54:18 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private boolean statusId;
     private Serializable description;
     private Set<Transaction> transactions = new HashSet<Transaction>(0);

    public Status() {
    }

	
    public Status(boolean statusId, Serializable description) {
        this.statusId = statusId;
        this.description = description;
    }
    public Status(boolean statusId, Serializable description, Set<Transaction> transactions) {
       this.statusId = statusId;
       this.description = description;
       this.transactions = transactions;
    }
   
    public boolean isStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(boolean statusId) {
        this.statusId = statusId;
    }
    public Serializable getDescription() {
        return this.description;
    }
    
    public void setDescription(Serializable description) {
        this.description = description;
    }
    public Set<Transaction> getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set<Transaction> transactions) {
        this.transactions = transactions;
    }




}


